version: '3.3'

services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - "27018:27017"
    networks:
      - my-network

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-container
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://mongodb:27017/"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
